### ISSUE TITLE
Create survey question array

### ISSUE THREAD

**Issue by siumairice** [slightlyskepticalpotat/actually-uwu#21]
add in survey questions:

doesn't matter how

add in survey options formatted like this:

const questionName = [
    { label: 'option name'},
    { label: 'option name'},
    { label: 'option name'},
    { label: 'option name'},
]

**Comment by 0foxes** [comment]
do you mean like https://docs.google.com/document/d/19zA14ccxyOUJgGcC_Gxnrjbl7Jx0yibMf4cECf7G-2A/edit#heading=h.aiz5ru44eyzk
