### ISSUE TITLE
integrate weather apis

### ISSUE THREAD

**Issue by Skylarrji** [slightlyskepticalpotat/actually-uwu#6]
- research + integrate some apis that fetch the weather data based on the user's current location as well as generating some weather fun facts(?, not sure if we need an API for that)

**Comment by 0foxes** [comment]
suggested weather api: openweather is easy to use

**Comment by Skylarrji** [comment]
![Image](https://github.com/siumairice/actually-useful-weather-app/assets/72311728/fe80afd4-4595-4545-a7b4-471321d2ee79)

**Comment by Skylarrji** [comment]
https://www.weatherapi.com/api.aspx
https://open-meteo.com/

**Comment by Skylarrji** [comment]
https://docs.tomorrow.io/reference/welcome

**Comment by 0foxes** [comment]
we ended up using openweather
